USE [FuelStationDb];

CREATE TABLE FuelStations
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name NVARCHAR(150) NOT NULL,
	Address NVARCHAR(200) NOT NULL,
	City NVARCHAR(100) NOT NULL,
	NoteDescription NVARCHAR(500) NULL,
	IsActive BIT NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL
);
